# Generated by Django 3.0.5 on 2020-04-28 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.IntegerField(choices=[(1, 'Fruit'), (2, 'Vegetable'), (3, 'Protein'), (4, 'Dairy'), (5, 'Grains'), (6, 'Oils')])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IngredientsNutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.FloatField()),
                ('fat', models.FloatField()),
                ('saturates', models.FloatField()),
                ('carbs', models.FloatField()),
                ('sugar', models.FloatField()),
                ('fibre', models.FloatField()),
                ('protein', models.FloatField()),
                ('salt', models.FloatField()),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.Ingredient')),
            ],
            options={
                'ordering': ['ingredient_id'],
            },
        ),
    ]
