# Generated by Django 3.0.5 on 2020-04-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='measurement',
            field=models.IntegerField(choices=[(0, 'weight'), (1, 'volume'), (2, 'piece')]),
        ),
    ]
