# Generated by Django 3.0.5 on 2020-04-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0005_auto_20200428_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.IntegerField(choices=[(1, 'Fruit'), (2, 'Vegetable'), (3, 'Protein'), (4, 'Dairy'), (5, 'Grains'), (6, 'Oils'), (7, 'Seasoning'), (8, 'Spice'), (9, 'Other')]),
        ),
    ]
