# Generated by Django 3.0.5 on 2020-04-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0007_recipe_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='part',
            field=models.IntegerField(choices=[(0, 'Ingredients'), (1, 'Steps')], max_length=1),
        ),
    ]
