# Generated by Django 3.0.5 on 2020-04-28 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0009_auto_20200428_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='sectioon_id',
        ),
    ]
