# Generated by Django 3.0.5 on 2020-04-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0010_remove_step_sectioon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
