# Generated by Django 3.0.5 on 2020-05-17 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='description',
            new_name='introduction',
        ),
    ]
