# Generated by Django 3.0.5 on 2020-07-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilepic',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='userprofilepic',
            name='gcloud_bucket_url',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofilepic',
            name='profile_pic_url',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
