# Generated by Django 3.0.5 on 2020-07-06 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200706_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofilepic',
            old_name='profile_pic_url',
            new_name='url',
        ),
    ]
