# Generated by Django 3.0.5 on 2020-05-16 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='ingredientamount',
            old_name='section_id',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='section_id',
            new_name='section',
        ),
    ]
