# Generated by Django 3.0.5 on 2020-06-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='ingredient',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
