# Generated by Django 3.0.5 on 2020-07-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20200629_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
