# Generated by Django 3.0.5 on 2020-07-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20200702_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='gcloud_bucket_url',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
