# Generated by Django 3.0.5 on 2020-06-01 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20200601_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='path',
            new_name='url',
        ),
    ]
