# Generated by Django 3.0.5 on 2020-07-03 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0003_auto_20200702_1415'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user_follow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follow',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_user_follow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user_upvote', to=settings.AUTH_USER_MODEL)),
                ('target_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_recipe_upvote', to='recipe.Recipe')),
            ],
        ),
    ]
