# Generated by Django 3.0.5 on 2020-07-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20200727_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_at',
            new_name='commented_at',
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.IntegerField(choices=[(0, 'follow'), (1, 'rate'), (2, 'share'), (3, 'create'), (4, 'upvote'), (5, 'tried'), (6, 'comment')]),
        ),
    ]
