# Generated by Django 3.0.5 on 2020-07-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20200728_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-commented_at']},
        ),
        migrations.RenameField(
            model_name='like',
            old_name='target_post',
            new_name='target_id',
        ),
        migrations.AddField(
            model_name='like',
            name='target_type',
            field=models.IntegerField(choices=[(0, 'post'), (1, 'comment')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.IntegerField(choices=[(0, 'follow'), (1, 'rate'), (2, 'share'), (3, 'create'), (4, 'upvote'), (5, 'tried'), (6, 'comment'), (7, 'reply')]),
        ),
    ]
