# Generated by Django 3.0.5 on 2020-07-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_auto_20200728_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='target_type',
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.IntegerField(choices=[(0, 'follow'), (1, 'rate'), (2, 'share'), (3, 'create'), (4, 'upvote'), (5, 'try'), (6, 'comment'), (7, 'reply'), (8, 'like post')]),
        ),
    ]
