# Generated by Django 3.0.5 on 2020-07-28 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_auto_20200728_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='target_id',
            new_name='target_post',
        ),
    ]
