# Generated by Django 3.0.5 on 2020-08-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_dailyvisit_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='trending',
            name='num_visit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
