# Generated by Django 3.0.5 on 2020-08-10 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20200704_1043'),
        ('social', '0011_trending_num_visit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trending',
            new_name='RecipeTrending',
        ),
        migrations.RemoveField(
            model_name='recipetrending',
            name='post',
        ),
        migrations.AddField(
            model_name='recipetrending',
            name='recipe',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='recipe.Recipe'),
            preserve_default=False,
        ),
    ]
