# Generated by Django 3.0.5 on 2020-07-23 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmedia',
            name='name',
        ),
    ]
