# Generated by Django 3.0.5 on 2020-08-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_number_of_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='number_of_like',
            field=models.IntegerField(default=0),
        ),
    ]
